#!/bin/sh
# Post-remove script for git-unas.
set -e

case "$1" in
    purge)
        rm -rf /etc/git-unas /var/lib/git-unas
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

exit 0
